# Fourier Activation 

This notebook is used to explore some things needed for the Fourier Activation paper

I should write an entire paper on that and publish it.




In [1]:
import numpy as np
import math
import torch
import torch.nn as nn
from torch.nn import functional as F
from torch.nn.utils import weight_norm


In [2]:
factors = torch.Tensor(np.linspace(0.0001,2., 5)).unsqueeze(0)
phases = torch.Tensor(np.linspace(0.0001,2*np.pi, 5)).unsqueeze(0)
weights = torch.Tensor(np.linspace(0.0001,2., 5)).unsqueeze(0)

x = torch.Tensor(np.linspace(1,10., 10)).unsqueeze(0)

In [3]:
factors.shape, factors

(torch.Size([1, 5]),
 tensor([[1.0000e-04, 5.0007e-01, 1.0000e+00, 1.5000e+00, 2.0000e+00]]))

In [4]:
factors.transpose(0,1)

tensor([[1.0000e-04],
        [5.0007e-01],
        [1.0000e+00],
        [1.5000e+00],
        [2.0000e+00]])

In [5]:
fx = factors.transpose(0,1) * x

In [6]:
factors

tensor([[1.0000e-04, 5.0007e-01, 1.0000e+00, 1.5000e+00, 2.0000e+00]])

In [7]:
fx.shape

torch.Size([5, 10])

In [8]:
fx

tensor([[1.0000e-04, 2.0000e-04, 3.0000e-04, 4.0000e-04, 5.0000e-04, 6.0000e-04,
         7.0000e-04, 8.0000e-04, 9.0000e-04, 1.0000e-03],
        [5.0007e-01, 1.0001e+00, 1.5002e+00, 2.0003e+00, 2.5004e+00, 3.0004e+00,
         3.5005e+00, 4.0006e+00, 4.5007e+00, 5.0007e+00],
        [1.0000e+00, 2.0001e+00, 3.0001e+00, 4.0002e+00, 5.0002e+00, 6.0003e+00,
         7.0003e+00, 8.0004e+00, 9.0004e+00, 1.0000e+01],
        [1.5000e+00, 3.0001e+00, 4.5001e+00, 6.0001e+00, 7.5001e+00, 9.0002e+00,
         1.0500e+01, 1.2000e+01, 1.3500e+01, 1.5000e+01],
        [2.0000e+00, 4.0000e+00, 6.0000e+00, 8.0000e+00, 1.0000e+01, 1.2000e+01,
         1.4000e+01, 1.6000e+01, 1.8000e+01, 2.0000e+01]])

In [9]:
dephase = (x - phases.transpose(0,1))

In [10]:
phases

tensor([[1.0000e-04, 1.5709e+00, 3.1416e+00, 4.7124e+00, 6.2832e+00]])

In [11]:
dephase.shape, dephase

(torch.Size([5, 10]),
 tensor([[ 0.9999,  1.9999,  2.9999,  3.9999,  4.9999,  5.9999,  6.9999,  7.9999,
           8.9999,  9.9999],
         [-0.5709,  0.4291,  1.4291,  2.4291,  3.4291,  4.4291,  5.4291,  6.4291,
           7.4291,  8.4291],
         [-2.1416, -1.1416, -0.1416,  0.8584,  1.8584,  2.8584,  3.8584,  4.8584,
           5.8584,  6.8584],
         [-3.7124, -2.7124, -1.7124, -0.7124,  0.2876,  1.2876,  2.2876,  3.2876,
           4.2876,  5.2876],
         [-5.2832, -4.2832, -3.2832, -2.2832, -1.2832, -0.2832,  0.7168,  1.7168,
           2.7168,  3.7168]]))

In [12]:
torch.sum(fx, 0).shape

torch.Size([10])

In [13]:
torch.rand(())

tensor(0.6954)

In [14]:
p = nn.Parameter(torch.rand(10))

In [15]:
p

Parameter containing:
tensor([0.3410, 0.7670, 0.8774, 0.2877, 0.9563, 0.4387, 0.5013, 0.8888, 0.2293,
        0.9247], requires_grad=True)

In [16]:
v1 = torch.rand((10,10))
v2 = torch.rand((10)).unsqueeze(0)
v2b = torch.rand((10)).unsqueeze(1)

In [17]:
v1.shape, v2.shape, v2b.shape

(torch.Size([10, 10]), torch.Size([1, 10]), torch.Size([10, 1]))

In [18]:
torch.mm(v2,v1)

tensor([[2.7735, 1.5294, 3.0591, 3.0105, 2.9638, 2.6060, 1.6178, 3.1223, 1.9981,
         1.8340]])

In [19]:
torch.mm(v1,v2.transpose(0,1))

tensor([[2.8123],
        [1.9006],
        [3.2032],
        [2.8362],
        [3.0779],
        [2.5285],
        [2.9119],
        [2.3536],
        [1.8966],
        [2.3482]])

In [20]:
pwd

'/home/leo/projects/mix_nlp/utf8/notebooks'

In [21]:
cd /home/leo/projects/mix_nlp/utf8

/home/leo/projects/mix_nlp/utf8


In [22]:
ls

charsets/             data_loader.py   preprocessors/      trainer_helpers.py
checkpoints/          gutenberg_logs/  __pycache__/        trainer.py
codes/                __init__.py      runs/               utf8_encoder.py
conllu_stats.json.gz  model_blocks.py  sparse_decoders.py  utils.py
constants.py          models.py        sparse_encoders.py  word_modules.py
convolutions.py       notebooks/       tools.py


In [23]:
from word_modules import *

In [24]:
we = WordEncoder(in_lang_size=128, in_word_size=512,
                 hid_lang_size=2048, hid_word_size=2048, lat_word_size=300,
                 activation=None,
                 use_softmax=False,
                 )

In [25]:
from utils import * 
from tools import *

In [26]:
count_parameters(we)

4057967

In [29]:
wd = WordDecoder(in_lang_size=128, out_langvar_size=64, out_word_size=512,
                 hid_lang_size=2048, hid_word_size=2048, lat_word_size=300,
                 activation=None,
                 )


In [30]:
count_parameters(wd)

4951192