# Fourier Activation 

This notebook is used to explore some things needed for the Fourier Activation paper

I should write an entire paper on that and publish it.




In [1]:
import numpy as np
import math
import torch
import torch.nn as nn
from torch.nn import functional as F
from torch.nn.utils import weight_norm


In [34]:
factors = torch.Tensor(np.linspace(0.0001,2., 5)).unsqueeze(0)
phases = torch.Tensor(np.linspace(0.0001,2*np.pi, 5)).unsqueeze(0)
weights = torch.Tensor(np.linspace(0.0001,2., 5)).unsqueeze(0)

x = torch.Tensor(np.linspace(1,10., 10)).unsqueeze(0)

In [35]:
factors.shape, factors

(torch.Size([1, 5]),
 tensor([[1.0000e-04, 5.0007e-01, 1.0000e+00, 1.5000e+00, 2.0000e+00]]))

In [36]:
factors.transpose(0,1)

tensor([[1.0000e-04],
        [5.0007e-01],
        [1.0000e+00],
        [1.5000e+00],
        [2.0000e+00]])

In [37]:
fx = factors.transpose(0,1) * x

In [42]:
factors

tensor([[1.0000e-04, 5.0007e-01, 1.0000e+00, 1.5000e+00, 2.0000e+00]])

In [38]:
fx.shape

torch.Size([5, 10])

In [41]:
fx

tensor([[1.0000e-04, 2.0000e-04, 3.0000e-04, 4.0000e-04, 5.0000e-04, 6.0000e-04,
         7.0000e-04, 8.0000e-04, 9.0000e-04, 1.0000e-03],
        [5.0007e-01, 1.0001e+00, 1.5002e+00, 2.0003e+00, 2.5004e+00, 3.0004e+00,
         3.5005e+00, 4.0006e+00, 4.5007e+00, 5.0007e+00],
        [1.0000e+00, 2.0001e+00, 3.0001e+00, 4.0002e+00, 5.0002e+00, 6.0003e+00,
         7.0003e+00, 8.0004e+00, 9.0004e+00, 1.0000e+01],
        [1.5000e+00, 3.0001e+00, 4.5001e+00, 6.0001e+00, 7.5001e+00, 9.0002e+00,
         1.0500e+01, 1.2000e+01, 1.3500e+01, 1.5000e+01],
        [2.0000e+00, 4.0000e+00, 6.0000e+00, 8.0000e+00, 1.0000e+01, 1.2000e+01,
         1.4000e+01, 1.6000e+01, 1.8000e+01, 2.0000e+01]])

In [45]:
dephase = (x - phases.transpose(0,1))

In [46]:
phases

tensor([[1.0000e-04, 1.5709e+00, 3.1416e+00, 4.7124e+00, 6.2832e+00]])

In [47]:
dephase.shape, dephase

(torch.Size([5, 10]),
 tensor([[ 0.9999,  1.9999,  2.9999,  3.9999,  4.9999,  5.9999,  6.9999,  7.9999,
           8.9999,  9.9999],
         [-0.5709,  0.4291,  1.4291,  2.4291,  3.4291,  4.4291,  5.4291,  6.4291,
           7.4291,  8.4291],
         [-2.1416, -1.1416, -0.1416,  0.8584,  1.8584,  2.8584,  3.8584,  4.8584,
           5.8584,  6.8584],
         [-3.7124, -2.7124, -1.7124, -0.7124,  0.2876,  1.2876,  2.2876,  3.2876,
           4.2876,  5.2876],
         [-5.2832, -4.2832, -3.2832, -2.2832, -1.2832, -0.2832,  0.7168,  1.7168,
           2.7168,  3.7168]]))

In [50]:
torch.sum(fx, 0).shape

torch.Size([10])

In [52]:
torch.rand(())

tensor([])